# Generated by Django 4.0.4 on 2022-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guard'), (2, 'Mess Manager'), (4, 'Hostel Secretary')], default=1),
        ),
    ]
