# Generated by Django 4.0.3 on 2022-05-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_guardtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardtoken',
            options={'verbose_name': 'Guard Token', 'verbose_name_plural': 'Guard Tokens'},
        ),
    ]
