# Generated by Django 4.0.4 on 2022-08-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_guardtoken_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Staff Token',
                'verbose_name_plural': 'Staff Tokens',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Guard',
            new_name='Staff',
        ),
        migrations.DeleteModel(
            name='GuardToken',
        ),
        migrations.AddField(
            model_name='stafftoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='authentication.staff', verbose_name='Staff'),
        ),
    ]
