# Generated by Django 4.0.4 on 2022-08-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_stafftoken_rename_guard_staff_delete_guardtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guard'), (2, 'Mess Manager')], default=1),
        ),
    ]
