# Generated by Django 4.0.4 on 2022-09-24 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Token',
                'verbose_name_plural': 'User Tokens',
                'abstract': False,
            },
        ),
    ]
