# Generated by Django 4.0.4 on 2022-09-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user_instance',
            new_name='user',
        ),
    ]
