# Generated by Django 4.0.4 on 2022-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_user_instance_usertoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Admin'), (1, 'Student'), (2, 'Employee'), (4, 'SWO Office'), (5, 'Academic Office UG'), (6, 'Academic Office PG'), (7, 'Gymkhana'), (8, 'Cultural Board'), (9, 'Technical Board'), (10, 'Sports Board'), (11, 'Hostel Board'), (12, 'Academic Board UG'), (13, 'Academic Board PG'), (14, 'IRA Team'), (15, 'Hostel Secretary')], default=3, null=True),
        ),
    ]
