# Generated by Django 4.0.4 on 2022-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Guard'), (2, 'Mess Manager'), (3, 'Medical Manager'), (4, 'Security Officer')], default=1),
        ),
    ]
