// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_vaLPSshmxXu8Eq3N43BECbhsYKO6SU',
    appId: '1:1053484742850:web:fa16d00f42cbfb8565a35b',
    messagingSenderId: '1053484742850',
    projectId: 'ira-test-project-355414',
    authDomain: 'ira-test-project-355414.firebaseapp.com',
    storageBucket: 'ira-test-project-355414.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCvCa5j7za8hiwupk4oxPc0iZNoQk5VAM',
    appId: '1:1053484742850:android:0cac645611f73e3c65a35b',
    messagingSenderId: '1053484742850',
    projectId: 'ira-test-project-355414',
    storageBucket: 'ira-test-project-355414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzF9PVFnRyi4CCIbp5hb085BEwklneF0',
    appId: '1:1053484742850:ios:af30ed751c95915865a35b',
    messagingSenderId: '1053484742850',
    projectId: 'ira-test-project-355414',
    storageBucket: 'ira-test-project-355414.appspot.com',
    androidClientId: '1053484742850-akcbtpdm0ao1bg1h6vfp3mrg7p457914.apps.googleusercontent.com',
    iosClientId: '1053484742850-m5e527ug5sjov4vh7k4kl5p9sbn9jf7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.instituteApp',
  );
}
