// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4UZXAdcLq7qXDSHGPo1dlyoAcWa12c38',
    appId: '1:76799423059:android:82135dce4b7b966c0ecca6',
    messagingSenderId: '76799423059',
    projectId: 'ira-app-c1428',
    storageBucket: 'ira-app-c1428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAlboxdfK3EEiyBDnuzkfuuJ3WxcmUj8',
    appId: '1:76799423059:ios:6d566a1beade5ec40ecca6',
    messagingSenderId: '76799423059',
    projectId: 'ira-app-c1428',
    storageBucket: 'ira-app-c1428.appspot.com',
    androidClientId: '76799423059-269uc17mm313rme6vkkgkt27n4fuhsha.apps.googleusercontent.com',
    iosClientId: '76799423059-2goq4dqnr2k67vbaonjibctv5bivv79a.apps.googleusercontent.com',
    iosBundleId: 'com.example.instituteApp',
  );
}
