# Generated by Django 4.0.4 on 2022-08-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfeedback',
            name='mess_type',
        ),
    ]
