# Generated by Django 4.0.4 on 2022-09-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='mess_meal',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
