# Generated by Django 4.0.4 on 2022-08-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messtender',
            old_name='archived',
            new_name='archieved',
        ),
        migrations.RemoveField(
            model_name='menuslot',
            name='items',
        ),
        migrations.RemoveField(
            model_name='weekday',
            name='slots',
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='mess.menuitem')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mess.menuslot')),
                ('weekdays', models.ManyToManyField(to='mess.weekday')),
            ],
        ),
    ]
