# Generated by Django 4.0.4 on 2023-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='fork-plate-and-knife.png', upload_to='mess_menu_items/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
