# Generated by Django 4.0.4 on 2022-08-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_remove_messfeedback_mess_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='mess_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.mess'),
        ),
    ]
