# Generated by Django 4.0.4 on 2023-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_menuitem_description_menuitem_image_menuitem_veg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='fork-plate-and-knife.png', upload_to='mess_menu_items/'),
        ),
    ]
