# Generated by Django 4.1 on 2022-09-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_rename_archived_messtender_archieved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfeedback',
            name='mess_meal',
        ),
    ]
