# Generated by Django 4.0.4 on 2022-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_remove_menuitem_slot_menuitem_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='week_day',
        ),
        migrations.AddField(
            model_name='menuslot',
            name='items',
            field=models.ManyToManyField(to='mess.menuitem'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='slot',
            field=models.ManyToManyField(to='mess.menuslot'),
        ),
    ]
