# Generated by Django 4.0.4 on 2023-03-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='mess_menu_items/fork-plate-and-knife.png', upload_to='mess_menu_items/'),
        ),
    ]
