# Generated by Django 4.1 on 2022-09-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_remove_messfeedback_mess_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='messfeedback',
            name='mess_meal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
