# Generated by Django 4.0.4 on 2022-06-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_mess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='slot',
            new_name='slots',
        ),
    ]
