# Generated by Django 4.0.4 on 2022-08-09 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0007_messmom_messtender_rename_body_feedback_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='MessFeedback',
        ),
    ]
