# Generated by Django 3.1.3 on 2022-08-13 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_auto_20220811_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='mess_no',
        ),
        migrations.AddField(
            model_name='feedback',
            name='mess_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
