# Generated by Django 4.1 on 2022-08-19 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0010_messtender_archived_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mess_meal',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
