# Generated by Django 4.0.4 on 2022-07-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('designation', models.CharField(default='', max_length=30)),
                ('profile', models.URLField()),
                ('linkedIn_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
    ]
