# Generated by Django 4.0.4 on 2022-07-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.CharField(max_length=100),
        ),
    ]
