# Generated by Django 4.0.4 on 2022-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStaffContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
