# Generated by Django 4.0.4 on 2022-09-05 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfeedback',
            name='complaint_type',
        ),
        migrations.RemoveField(
            model_name='hostelfeedback',
            name='status',
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('complaint_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.complainttype')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
