# Generated by Django 4.0.4 on 2022-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_maintenancestaffcontacts_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancestaffcontacts',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
