# Generated by Django 4.0.4 on 2022-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_remove_hostelfeedback_complaint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelcomplaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
