# Generated by Django 3.1.3 on 2022-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_maintenancestaffcontacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancestaffcontacts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
