# Generated by Django 4.0.4 on 2022-08-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_complainttype_hostel_hostelfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttype',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
