# Generated by Django 4.0.4 on 2022-08-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_alter_complainttype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelfeedback',
            name='hostel_no',
        ),
        migrations.AddField(
            model_name='hostelfeedback',
            name='hostel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
    ]
