# Generated by Django 4.0.4 on 2022-08-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_remove_hostelfeedback_hostel_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelfeedback',
            name='complaint_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.complainttype'),
        ),
        migrations.AlterField(
            model_name='hostelfeedback',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
    ]
