# Generated by Django 4.0.4 on 2022-09-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='inhouse',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='time',
        ),
    ]
