# Generated by Django 4.1 on 2022-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicalhistory_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='acceptance',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'in process'), (2, 'accepted'), (3, 'rejected')], default=1),
        ),
    ]
