# Generated by Django 4.0.4 on 2022-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_doctor_details_alter_doctor_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='specialization',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='details',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
