# Generated by Django 4.0.4 on 2022-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_remove_medicalhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='inhouse',
            field=models.BooleanField(default=False),
        ),
    ]
