# Generated by Django 4.1 on 2022-09-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_remove_appointment_acceptance_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'In process'), (2, 'Approved')], default=1),
        ),
    ]
