# Generated by Django 4.0.4 on 2022-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
