# Generated by Django 4.0.4 on 2022-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='prescription',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In progress'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='IN PROGRESS', max_length=30),
        ),
    ]
