# Generated by Django 4.1 on 2022-09-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_appointment_status'),
        ('medical', '0006_remove_medicalhistory_prescription_and_more'),
    ]

    operations = [
    ]
