# Generated by Django 4.0.4 on 2022-09-13 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_remove_medicalhistory_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
