# Generated by Django 4.1 on 2022-09-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_merge_20220915_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('IN PROGRESS', 'In progress'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='IN PROGRESS', max_length=30),
        ),
    ]
