# Generated by Django 4.0.4 on 2022-09-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_doctor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
    ]
