# Generated by Django 4.0.4 on 2022-09-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_alter_appointment_status'),
        ('medical', '0008_remove_doctor_age'),
    ]

    operations = [
    ]
