# Generated by Django 4.0.4 on 2022-06-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_no',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='valid_upto',
            field=models.DateField(default=None),
        ),
    ]
