# Generated by Django 4.0.4 on 2022-06-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_student_date_of_birth_alter_student_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='valid_upto',
            field=models.DateField(),
        ),
    ]
