# Generated by Django 4.0.4 on 2022-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_pass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
