# Generated by Django 4.0.4 on 2022-11-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_pass', '0002_gatepass_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['created_at']},
        ),
    ]
