# Generated by Django 4.0.4 on 2022-11-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_pass', '0003_alter_gatepass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={},
        ),
    ]
