# Generated by Django 4.0.4 on 2022-11-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate_pass', '0004_alter_gatepass_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'get_latest_by': ['created_at']},
        ),
    ]
