# Generated by Django 4.0.4 on 2022-10-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_document_post_post_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.document'),
            preserve_default=False,
        ),
    ]
