# Generated by Django 4.0.4 on 2022-10-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_attachments_post_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.document'),
        ),
    ]
