# Generated by Django 4.0.4 on 2022-10-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_alter_post_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(to='feed.document'),
        ),
    ]
